
# Name of your site (displayed in the header)
name: Puppy Snuggles

# Short bio or description (displayed in the header)
description: for those who love snuggling with puppies!

navlinks:
  - text: Blog
    url: blog/
  - text: Twitter
    url: twitter/
  - text: Facebook
    url: facebook/
  - text: Shop
    url: shop/
  - text: T-shirts
    url: tshirts/
    
frontpagelinks:
  - title: Blog
    url: /blog/
    img: /images/t-shirts.png 
  - title: Shop
    url: /shop/
    img: /images/t-shirts.png    
  - title: T-shirts
    url: /tshirts/
    img: /images/t-shirts.png
    
keywords:
  - puppy
  - puppies
  - dog
  - dogs
  - doggie
  - doggy
  - snuggle
  - snuggles
  - puppy snuggles
    
fb-app-id: 380905068954806
twitter: Puppy_Snuggles

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
# url: https://hendrixjoseph.github.io/puppy-snuggles
url: http://www.puppy-snuggles.com

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

paginate: 5
paginate_path: "/blog/page:num"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed #:expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
