
# Name of your site (displayed in the header)
name: Puppy Snuggles

# Short bio or description (displayed in the header)
description: for those who love snuggling with puppies!

navlinks:
  - text: Blog
    url: blog/
  - text: Shop
    url: shop/
  - text: T-Shirts
    url: tshirts/

frontpagelinks:
  - title: Blog
    url: /blog/
    img: /images/blog.png
    description: Here on the blog section of Puppy Snuggles, I talk about all things dogs - from personal stories to product reviews, and everything in between! Come and join the fun!
  - title: Shop
    url: /shop/
    img: /images/shop.png
    description: Shop all things for your pup - from treats to beds to cages and more!
  - title: T-Shirts
    url: /tshirts/
    img: /images/t-shirts.png
    description: Wear the coolest dog-related t-shirts, sweatshirts, and hoodies!

keywords:
  - puppy
  - puppies
  - dog
  - dogs
  - doggie
  - doggy
  - snuggle
  - snuggles
  - puppy snuggles

sociallinks:
    - what: Facebook
      url: https://www.facebook.com/puppysnuggle
      icon: fab fa-facebook-square
      color: \#3B5998
    - what: Instagram
      url: https://www.instagram.com/puppy.snuggles/
      icon: fab fa-instagram
      color: \#e4405f
    - what: Pinterest
      url: https://www.pinterest.com/puppysnuggles12/
      icon: fab fa-pinterest-square
      color: \#C92228
    - what: Twitter
      url: https://twitter.com/puppy_snuggles
      icon: fab fa-twitter-square
      color: \#1DA1F2
    - what: RSS
      url: https://www.puppy-snuggles.com/feed.xml
      icon: fas fa-rss
      color: orange

fb-app-id: 380905068954806
twitter: Puppy_Snuggles

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
# url: https://hendrixjoseph.github.io/puppy-snuggles
url: https://www.puppy-snuggles.com

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

# paginate: 5
# paginate_path: "/blog/page:num"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed #:expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
