name: Randomly share an RSS item.
on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  share:
    name: Randomly share an RSS item.
    runs-on: ubuntu-latest
    steps:
      - uses: hendrixjoseph/random-social-share@master
        with:
          source: https://news.puppy-snuggles.com/feed
          facebook_access_token: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
