name: Randomly share an RSS item.

# Controls when the action will run. 
on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  share:
    name: Randomly share an RSS item.
    runs-on: ubuntu-latest
    steps:
      - uses: LuisAlejandro/fb-random-post-from-feed@0.1.1
